spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chembase
    username: mmeziane
    password: password
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      elasticsearch:
        rest:
          uris: http://localhost:9200
  jpa:
    hibernate:
      ddl-auto: update  # of create, validate, none, afhankelijk van je behoeften
    show-sql: true      # Zet dit op true om SQL-queries te loggen
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Pas dit aan voor jouw database
  logging:
    level:
      root: DEBUG
  server:
    port: 8081  # of een andere beschikbare poort