spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chembase
    username: mmeziane
    password: password
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      elasticsearch:
        rest:
          uris: http://localhost:9200